# Generated by Django 3.2.6 on 2021-08-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('start_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('end_time', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
