# Generated by Django 3.2.6 on 2021-08-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_event_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
    ]
